branches:
  only:
  - master
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
deploy:
  user: rafaelpivato
  provider: pypi
  password:
    secure: D7gJpjQMx0KEYZCdlmLzjLGy4fB67xZ7Vd74AdePQua9qmzsMLxLl6O8iF11dm5/9oTS3vuUtxAetV/MUK1msEO2mvnJddujMJ9VpeFwkv99i9Ua1PEBAlW732CyWa7zDWjd4P+/MU/Gm5rQPYLbwaYpy7UAXzFpCeRtjafPxY6/dlmSEttVImOuVRIOswgww+Q08dlEnim0SY6TH4OsWf7eEuFVOYW1G+iLl8mg6yt/YaSbyl9lWt8h0B3twJ8v86vSzxVSUC07d8Rd0WO+jYC00qX6xx0tZK+sCvVgid4UW/G8r6dYzLbaOdPQTUvbj+n7TvXuMZpBESrJj8d/pfd6W1QbfylfOF3as/0u2JYTtfbwYNqBTIWOMHnenpl/6kb+dC5zynpnrViIgS4PincaLgPjBqHveBXdOPU2WqhjAj6Aj2swB+XtopiYopD3Wpl7foFhF67C1pFHk3lZMO7c2y8RBT+RgcNoUJp23qONDCalR4dJDwTThfs44EDuji1kbEmwnzMcpvQj/NJgaiDfSnvq06pUUCEdkm1KF31NAegGHaxW44UvRZu8y6npozD15QqPd44wUez1Vm8aO+lb/VXGIbB7zI8eEvv40YvRkkfozgjVa9aU7VYDAO4lOwpDYAA8CF1BMrSHrlA5PMxNUyBaoBeH7Q+6izr1Pmg=
  distributions: sdist bdist_wheel
  on:
    repo: pyupio/changelogs
    tags: true
    python: '3.7'
language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install codecov flake8 tox-travis
script:
- tox
after_success:
- codecov
- flake8
